repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: detect-aws-credentials
        args:
            - --allow-missing-credentials
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
    -   id: ruff-check
        types: [file]
        types_or: [file]
        files: 'dot_bin/executable_plex-sync'
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck
        types: [file]
        files: 'dot_bin/executable_|dot_config/rustbin|run_.*\.sh'
        exclude: '(\.tmpl$|executable_plex-sync)'
        args: [-x]
